name: Always Workflow

on:
  workflow_dispatch

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Previous step that may fail
        run: echo "This step might fail"

      - name: Step that always runs
        if: always()
        run: echo "This step runs even if the previous one fails"
