# This is a basic workflow to help you get started with Actions

name: MacArtifactUploadTest

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test-upload-artifact:
    # The type of runner that the job will run on
    runs-on: mac-runner-1
    steps:
        - name: Create files (500MiB)
          run: |
            dd if=/dev/urandom of=artifact bs=1M count=500
            dd if=/dev/zero of=artifact-unsigned bs=1M count=1
        - name: upload artifact
          uses: actions/upload-artifact@v4
          with:
            name: urandom
            compression-level: 0
            retention-days: 1
            path: |
              artifact
              !*-unsigned*
